//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_pedido
    {
        public int id_detalle { get; set; }
        public Nullable<int> pedido_id { get; set; }
        public Nullable<int> menu_id { get; set; }
    
        public virtual menu menu { get; set; }
        public virtual pedido pedido { get; set; }
    }
}
