//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public menu()
        {
            this.detalle_pedido = new HashSet<detalle_pedido>();
        }
    
        public int id_menu { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> precio { get; set; }
    
        public virtual ICollection<detalle_pedido> detalle_pedido { get; set; }
    }
}
