//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaSQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public int id_venta { get; set; }
        public Nullable<int> subtotal { get; set; }
        public int propina { get; set; }
        public Nullable<int> total { get; set; }
        public Nullable<int> pedido_id { get; set; }
        public Nullable<System.DateTime> fecha_venta { get; set; }
    
        public virtual pedido pedido { get; set; }
    }
}
