//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vista.Service_Venta_BackUp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Servicios/", ConfigurationName="Service_Venta_BackUp.NewWebService")]
    public interface NewWebService {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/NewWebService/crearVentaRequest", ReplyAction="http://Servicios/NewWebService/crearVentaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        vista.Service_Venta_BackUp.crearVentaResponse crearVenta(vista.Service_Venta_BackUp.crearVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/NewWebService/crearVentaRequest", ReplyAction="http://Servicios/NewWebService/crearVentaResponse")]
        System.Threading.Tasks.Task<vista.Service_Venta_BackUp.crearVentaResponse> crearVentaAsync(vista.Service_Venta_BackUp.crearVentaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/NewWebService/listarVentasRequest", ReplyAction="http://Servicios/NewWebService/listarVentasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        vista.Service_Venta_BackUp.listarVentasResponse listarVentas(vista.Service_Venta_BackUp.listarVentasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/NewWebService/listarVentasRequest", ReplyAction="http://Servicios/NewWebService/listarVentasResponse")]
        System.Threading.Tasks.Task<vista.Service_Venta_BackUp.listarVentasResponse> listarVentasAsync(vista.Service_Venta_BackUp.listarVentasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/NewWebService/buscarVentaRequest", ReplyAction="http://Servicios/NewWebService/buscarVentaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        vista.Service_Venta_BackUp.buscarVentaResponse buscarVenta(vista.Service_Venta_BackUp.buscarVentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Servicios/NewWebService/buscarVentaRequest", ReplyAction="http://Servicios/NewWebService/buscarVentaResponse")]
        System.Threading.Tasks.Task<vista.Service_Venta_BackUp.buscarVentaResponse> buscarVentaAsync(vista.Service_Venta_BackUp.buscarVentaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearVenta", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class crearVentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int subtot;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int propin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int total_r;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int pedido_id;
        
        public crearVentaRequest() {
        }
        
        public crearVentaRequest(int idd, int subtot, int propin, int total_r, int pedido_id) {
            this.idd = idd;
            this.subtot = subtot;
            this.propin = propin;
            this.total_r = total_r;
            this.pedido_id = pedido_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="crearVentaResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class crearVentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public crearVentaResponse() {
        }
        
        public crearVentaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Servicios/")]
    public partial class ventasBackup : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal idResField;
        
        private bool idResFieldSpecified;
        
        private string pedidoidResField;
        
        private string propinaResField;
        
        private string subtotalResField;
        
        private string totalResField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal idRes {
            get {
                return this.idResField;
            }
            set {
                this.idResField = value;
                this.RaisePropertyChanged("idRes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idResSpecified {
            get {
                return this.idResFieldSpecified;
            }
            set {
                this.idResFieldSpecified = value;
                this.RaisePropertyChanged("idResSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=1)]
        public string pedidoidRes {
            get {
                return this.pedidoidResField;
            }
            set {
                this.pedidoidResField = value;
                this.RaisePropertyChanged("pedidoidRes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=2)]
        public string propinaRes {
            get {
                return this.propinaResField;
            }
            set {
                this.propinaResField = value;
                this.RaisePropertyChanged("propinaRes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=3)]
        public string subtotalRes {
            get {
                return this.subtotalResField;
            }
            set {
                this.subtotalResField = value;
                this.RaisePropertyChanged("subtotalRes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer", Order=4)]
        public string totalRes {
            get {
                return this.totalResField;
            }
            set {
                this.totalResField = value;
                this.RaisePropertyChanged("totalRes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarVentas", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class listarVentasRequest {
        
        public listarVentasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarVentasResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class listarVentasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public vista.Service_Venta_BackUp.ventasBackup[] @return;
        
        public listarVentasResponse() {
        }
        
        public listarVentasResponse(vista.Service_Venta_BackUp.ventasBackup[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarVenta", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class buscarVentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public buscarVentaRequest() {
        }
        
        public buscarVentaRequest(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarVentaResponse", WrapperNamespace="http://Servicios/", IsWrapped=true)]
    public partial class buscarVentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public buscarVentaResponse() {
        }
        
        public buscarVentaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NewWebServiceChannel : vista.Service_Venta_BackUp.NewWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewWebServiceClient : System.ServiceModel.ClientBase<vista.Service_Venta_BackUp.NewWebService>, vista.Service_Venta_BackUp.NewWebService {
        
        public NewWebServiceClient() {
        }
        
        public NewWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vista.Service_Venta_BackUp.crearVentaResponse vista.Service_Venta_BackUp.NewWebService.crearVenta(vista.Service_Venta_BackUp.crearVentaRequest request) {
            return base.Channel.crearVenta(request);
        }
        
        public int crearVenta(int idd, int subtot, int propin, int total_r, int pedido_id) {
            vista.Service_Venta_BackUp.crearVentaRequest inValue = new vista.Service_Venta_BackUp.crearVentaRequest();
            inValue.idd = idd;
            inValue.subtot = subtot;
            inValue.propin = propin;
            inValue.total_r = total_r;
            inValue.pedido_id = pedido_id;
            vista.Service_Venta_BackUp.crearVentaResponse retVal = ((vista.Service_Venta_BackUp.NewWebService)(this)).crearVenta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vista.Service_Venta_BackUp.crearVentaResponse> vista.Service_Venta_BackUp.NewWebService.crearVentaAsync(vista.Service_Venta_BackUp.crearVentaRequest request) {
            return base.Channel.crearVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<vista.Service_Venta_BackUp.crearVentaResponse> crearVentaAsync(int idd, int subtot, int propin, int total_r, int pedido_id) {
            vista.Service_Venta_BackUp.crearVentaRequest inValue = new vista.Service_Venta_BackUp.crearVentaRequest();
            inValue.idd = idd;
            inValue.subtot = subtot;
            inValue.propin = propin;
            inValue.total_r = total_r;
            inValue.pedido_id = pedido_id;
            return ((vista.Service_Venta_BackUp.NewWebService)(this)).crearVentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vista.Service_Venta_BackUp.listarVentasResponse vista.Service_Venta_BackUp.NewWebService.listarVentas(vista.Service_Venta_BackUp.listarVentasRequest request) {
            return base.Channel.listarVentas(request);
        }
        
        public vista.Service_Venta_BackUp.ventasBackup[] listarVentas() {
            vista.Service_Venta_BackUp.listarVentasRequest inValue = new vista.Service_Venta_BackUp.listarVentasRequest();
            vista.Service_Venta_BackUp.listarVentasResponse retVal = ((vista.Service_Venta_BackUp.NewWebService)(this)).listarVentas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vista.Service_Venta_BackUp.listarVentasResponse> vista.Service_Venta_BackUp.NewWebService.listarVentasAsync(vista.Service_Venta_BackUp.listarVentasRequest request) {
            return base.Channel.listarVentasAsync(request);
        }
        
        public System.Threading.Tasks.Task<vista.Service_Venta_BackUp.listarVentasResponse> listarVentasAsync() {
            vista.Service_Venta_BackUp.listarVentasRequest inValue = new vista.Service_Venta_BackUp.listarVentasRequest();
            return ((vista.Service_Venta_BackUp.NewWebService)(this)).listarVentasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        vista.Service_Venta_BackUp.buscarVentaResponse vista.Service_Venta_BackUp.NewWebService.buscarVenta(vista.Service_Venta_BackUp.buscarVentaRequest request) {
            return base.Channel.buscarVenta(request);
        }
        
        public int buscarVenta(int id) {
            vista.Service_Venta_BackUp.buscarVentaRequest inValue = new vista.Service_Venta_BackUp.buscarVentaRequest();
            inValue.id = id;
            vista.Service_Venta_BackUp.buscarVentaResponse retVal = ((vista.Service_Venta_BackUp.NewWebService)(this)).buscarVenta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<vista.Service_Venta_BackUp.buscarVentaResponse> vista.Service_Venta_BackUp.NewWebService.buscarVentaAsync(vista.Service_Venta_BackUp.buscarVentaRequest request) {
            return base.Channel.buscarVentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<vista.Service_Venta_BackUp.buscarVentaResponse> buscarVentaAsync(int id) {
            vista.Service_Venta_BackUp.buscarVentaRequest inValue = new vista.Service_Venta_BackUp.buscarVentaRequest();
            inValue.id = id;
            return ((vista.Service_Venta_BackUp.NewWebService)(this)).buscarVentaAsync(inValue);
        }
    }
}
